---
driver:
  name: ec2
  aws_ssh_key_id: sing102aws
  security_group_ids: ["sg-25024a4c"]
  region: eu-central-1
  availability_zone: a
  require_chef_omnibus: true
  subnet_id: subnet-0ecf2f67
  iam_profile_name: TestKitchenRole
  instance_type: t2.small
#  price: 0.6
  associate_public_ip: true
  interface: dns
  tags:
    Name: "monitor_test"

transport:
#  ssh_key: /path/to/id_rsa-aws
  connection_timeout: 10
  connection_retries: 5
  name: speedy_ssh
  username: ubuntu

platforms:
  - name: ubuntu-14.04
    driver:
      image_id: ami-09618e66
    attributes:
      monitor:
        redis_address: sensu-redis.utgwtc.ng.0001.euc1.cache.amazonaws.com
        transport: snssqs
        snssqs_publishing_sns_topic_arn: 'arn:aws:sns:eu-central-1:001579709704:sensu-client-1'
        snssqs_consuming_sqs_queue_url: 'https://sqs.eu-central-1.amazonaws.com/001579709704/sensu-server'
    run_list:
      - recipe[aws::ec2_hints]
  - name: sles12
    driver:
      image_id: ami-2af53a45
    attributes:
      monitor:
        redis_address: sensu-redis.utgwtc.ng.0001.euc1.cache.amazonaws.com
        transport: snssqs
        snssqs_publishing_sns_topic_arn: 'arn:aws:sns:eu-central-1:001579709704:sensu-client-1'
        snssqs_consuming_sqs_queue_url: 'https://sqs.eu-central-1.amazonaws.com/001579709704/sensu-server'
    run_list:
      - recipe[aws::ec2_hints]
