---
driver:
  name: ec2
  instance_type: t2.micro
  region: eu-central-1
  iam_profile_name: chef-full-access-role-test
  associate_public_ip: true
  interface: dns
  require_chef_omnibus: true
#  price: 0.6
  tags:
    Name: "monitor_test"

transport:
#  ssh_key: /path/to/id_rsa-aws
  ssh_key: <%= "#{ENV['HOME']}/.ssh/#{ENV.fetch('KITCHEN_EC2_SSH_KEY_FILE', "#{ENV.fetch('USER', '')}aws")}" %>
  connection_timeout: 10
  connection_retries: 5
  username: ubuntu

platforms:
  - name: ubuntu-14.04
    driver:
      image_id: ami-09618e66
    attributes:
      monitor:
        redis_address: sensu-redis.utgwtc.ng.0001.euc1.cache.amazonaws.com
        transport: snssqs
        snssqs_publishing_sns_topic_arn: 'arn:aws:sns:eu-central-1:001579709704:sensu-client-1'
        snssqs_consuming_sqs_queue_url: 'https://sqs.eu-central-1.amazonaws.com/001579709704/sensu-server'
    run_list:
      - recipe[aws::ec2_hints]
  
