---
driver:
  name: ec2
  instance_type: t2.small
  region: eu-central-1
  iam_profile_name: chef-full-access-role-test
  associate_public_ip: true
  interface: dns
  require_chef_omnibus: true
#  price: 0.6
  tags:
    Name: "monitor_test"

transport:
#  ssh_key: /path/to/id_rsa-aws
  ssh_key: <%= "#{ENV['HOME']}/.ssh/#{ENV.fetch('KITCHEN_EC2_SSH_KEY_FILE', "#{ENV.fetch('USER', '')}aws")}" %>
  connection_timeout: 10
  connection_retries: 5
  username: ubuntu

platforms:
  - name: ubuntu-14.04
    transport.user: ubuntu
    driver:
      image_search:
        owner-id: "001579709704"
        name: "asy-ubuntu-1404-chef-sensu*"
    attributes:
      asy-base:
        mount:
          data:
            enabled: true
  - name: ubuntu-16.04
    transport.user: ubuntu
    driver:
      image_search:
        owner-id: "001579709704"
        name: "asy-ubuntu-1604-chef-sensu*"
    attributes:
      asy-base:
        mount:
          data:
            enabled: true
